name: Deploy To S3

on:
    push:
        branches: 
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
        
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'

            - name: Install Dependencies
              run: npm install

            - name: Build Project
              run: npm run build

            - name: AWS Credentials Configure
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: 'ap-south-1'

            # FIXED: Upload files with correct MIME types
            - name: Upload HTML files
              run: |
                aws s3 sync ./build s3://magic-magic-application \
                --exclude "*" --include "*.html" \
                --content-type "text/html" \
                --cache-control "max-age=0, no-cache, no-store, must-revalidate"

            - name: Upload JavaScript files  
              run: |
                aws s3 sync ./build s3://magic-magic-application \
                --exclude "*" --include "*.js" \
                --content-type "application/javascript" \
                --cache-control "max-age=31536000"

            - name: Upload CSS files
              run: |
                aws s3 sync ./build s3://magic-magic-application \
                --exclude "*" --include "*.css" \
                --content-type "text/css" \
                --cache-control "max-age=31536000"

            - name: Upload other static assets
              run: |
                aws s3 sync ./build s3://magic-magic-application \
                --exclude "*.html" --exclude "*.js" --exclude "*.css" \
                --cache-control "max-age=31536000"

            - name: Delete removed files
              run: aws s3 sync ./build s3://magic-magic-application --delete